apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: adamhayes/spg-reactui:0.1.11
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 1G

---

apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  type: NodePort
  clusterIP: 10.98.76.100
  selector:
    app: react-app
  ports:
  - port: 3000
    nodePort: 30008
