apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: adamhayes/spg-springapi:0.1.9
        ports:
        - containerPort: 8080
        resources:
          cpu: 500m
          memory: 1G

---

apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  type: NodePort
  clusterIP: 10.96.32.10
  selector:
    app: spring-app
  ports:
  - port: 8080
    nodePort: 30007
